### ISSUE TITLE
Install & Compilation

### ISSUE THREAD

**Issue by slyruss** [FeNoMeNa/cwmp-proxy#1]
Hello,
Yout project seems interesting but it's my first Go experience...
I created "src/github.com/FeNoMeNa/goha" and lunch 'go install' but I have an error log => "can't load package: import cycle not allowed"
Would you have an idea?

Thank you.

**Comment by FeNoMeNa** [comment]
Hi, 

Have you tried to get all dependencies of the cwmp-proxy?
Please read about `go get` (`go get github.com/FeNoMeNa/goha`)

Best regards

**Comment by FeNoMeNa** [comment]
You can build the project from `/cmd/cwmp-proxy` with `go build`

**Comment by slyruss** [comment]
Thank you for tips
